
--tabla de login 
CREATE TABLE ADM(
 ID INT PRIMARY KEY IDENTITY(1,1),
USUARIO VARCHAR(20),
CONTRASEÑA VARCHAR(20),
);

INSERT INTO ADM (usuario, Contraseña) VALUES ('ecuastock', '12345');

select * from ADM;

--tabla proveedor
CREATE TABLE USUARIOS(
RUC INT PRIMARY KEY,
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
DIRECCION VARCHAR(50),
TELEFONO VARCHAR(10),
CORREO VARCHAR(30),
GENERO VARCHAR(10),
FECHA_NACIMIENTO DATE
);

SELECT * FROM USUARIOS